name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: 1.8
    - name: Build Warehouse
      run: mvn --file warehouse/pom.xml install
    - name: Build Cakefactory
      run: mvn --file cakefactory/pom.xml install
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm install, build, and test
      run: |
        cd frontend
        npm install
        npm run build --if-present
        npm run test-with-mocks
